### ISSUE TITLE
Test config files: multiple variables

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#13]
- To test multiple variables in the config files:

```
plot3:
    timeseries:
        agent: Firm
        analysis: multiple_batch
        variables: 
              var1: [equity,equity_asset_ratio]  
        set: [range,[1,4,1]]
        run: [range,[1,2,1]]
        major: [range,[20,20000,20]]
        minor: [range,[1,80,1]]
        summary: sum
```
