### ISSUE TITLE
Check out-of-range for arrays

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#22]
Index values read-in from config.yaml file: check if index out-of-range

Examples
--

This works as it should:
```
plot0:
    timeseries:
        agent: Eurostat
        analysis: multiple_run
        variables:
            var1: [monthly_output]
        set: [1]
        run: [1]
        major: [range,[6020,12500,20]]
        minor: [0]
        summary: mean
```

This does not work due to `minor[1]`: This should throw an error
```
plot0:
    timeseries:
        agent: Eurostat
        analysis: multiple_run
        variables:
            var1: [monthly_output]
        set: [1]
        run: [1]
        major: [range,[6020,12500,20]]
        minor: [1]
        summary: mean
```
